export interface Product {
  id: string;
  category: string;
  title: string;
  imgDefault: string;
  imgHover: string;
  badge?: string;
  badgeClass?: string;
  rating: number;
  newPrice: string;
  oldPrice: string;
}

export const categories = [
  { name: "T-Shirt", img: "/img/category-1.jpg" },
  { name: "Bags", img: "/img/category-2.jpg" },
  { name: "Sandal", img: "/img/category-3.jpg" },
  { name: "Scarf Cap", img: "/img/category-4.jpg" },
  { name: "Shoes", img: "/img/category-5.jpg" },
  { name: "Pillowcase", img: "/img/category-6.jpg" },
  { name: "Jumpsuit", img: "/img/category-7.jpg" },
  { name: "Hats", img: "/img/category-8.jpg" },
];

export const featuredProducts: Product[] = [
  {
    id: "f1",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-1-1.jpg",
    imgHover: "/img/product-1-2.jpg",
    badge: "Hot",
    badgeClass: "light-pink",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "f2",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-2-1.jpg",
    imgHover: "/img/product-2-2.jpg",
    badge: "Hot",
    badgeClass: "light-green",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "f3",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-3-1.jpg",
    imgHover: "/img/product-3-2.jpg",
    badge: "Hot",
    badgeClass: "light-orange",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "f4",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-4-1.jpg",
    imgHover: "/img/product-4-2.jpg",
    badge: "Hot",
    badgeClass: "light-blue",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "f5",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-5-1.jpg",
    imgHover: "/img/product-5-2.jpg",
    badge: "-30%",
    badgeClass: "light-blue",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "f6",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-6-1.jpg",
    imgHover: "/img/product-6-2.jpg",
    badge: "-22%",
    badgeClass: "light-blue",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "f7",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-7-1.jpg",
    imgHover: "/img/product-7-2.jpg",
    badge: "-22%",
    badgeClass: "light-green",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "f8",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-8-1.jpg",
    imgHover: "/img/product-8-2.jpg",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
];

export const popularProducts: Product[] = [
  {
    id: "p1",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-9-1.jpg",
    imgHover: "/img/product-9-2.jpg",
    badge: "Hot",
    badgeClass: "light-pink",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "p2",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-2-1.jpg",
    imgHover: "/img/product-2-2.jpg",
    badge: "Hot",
    badgeClass: "light-green",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "p3",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-10-1.jpg",
    imgHover: "/img/product-10-2.jpg",
    badge: "Hot",
    badgeClass: "light-orange",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "p4",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-4-1.jpg",
    imgHover: "/img/product-4-2.jpg",
    badge: "Hot",
    badgeClass: "light-blue",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "p5",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-5-1.jpg",
    imgHover: "/img/product-5-2.jpg",
    badge: "-30%",
    badgeClass: "light-blue",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "p6",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-11-1.jpg",
    imgHover: "/img/product-11-2.jpg",
    badge: "-22%",
    badgeClass: "light-blue",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "p7",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-7-1.jpg",
    imgHover: "/img/product-7-2.jpg",
    badge: "-22%",
    badgeClass: "light-green",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "p8",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-8-1.jpg",
    imgHover: "/img/product-8-2.jpg",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
];

export const newAddedProducts: Product[] = [
  {
    id: "n1",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-1-1.jpg",
    imgHover: "/img/product-1-2.jpg",
    badge: "Hot",
    badgeClass: "light-pink",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "n2",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-12-1.jpg",
    imgHover: "/img/product-12-2.jpg",
    badge: "Hot",
    badgeClass: "light-green",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "n3",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-3-1.jpg",
    imgHover: "/img/product-3-2.jpg",
    badge: "Hot",
    badgeClass: "light-orange",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "n4",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-13-1.jpg",
    imgHover: "/img/product-13-2.jpg",
    badge: "Hot",
    badgeClass: "light-blue",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "n5",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-5-1.jpg",
    imgHover: "/img/product-5-2.jpg",
    badge: "-30%",
    badgeClass: "light-blue",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "n6",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-6-1.jpg",
    imgHover: "/img/product-6-2.jpg",
    badge: "-22%",
    badgeClass: "light-blue",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "n7",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-7-1.jpg",
    imgHover: "/img/product-7-2.jpg",
    badge: "-22%",
    badgeClass: "light-green",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
  {
    id: "n8",
    category: "Clothing",
    title: "Colorful Pattern Shirts",
    imgDefault: "/img/product-8-1.jpg",
    imgHover: "/img/product-8-2.jpg",
    rating: 5,
    newPrice: "$238.85",
    oldPrice: "$245.8",
  },
];

export const showcaseGroups = [
  {
    title: "Hot Releases",
    items: [
      {
        title: "Colorful Pattern Shirt",
        price: "$238.85",
        rating: 4,
        img: "/img/showcase-img-1.jpg",
      },
      {
        title: "Sleek Floral Blouse",
        price: "$120.00",
        rating: 5,
        img: "/img/showcase-img-2.jpg",
      },
      {
        title: "Classic Denim Jacket",
        price: "$340.50",
        rating: 4,
        img: "/img/showcase-img-3.jpg",
      },
    ],
  },
  {
    title: "Trending Now",
    items: [
      {
        title: "Casual Stripe Tee",
        price: "$95.00",
        rating: 5,
        img: "/img/showcase-img-4.jpg",
      },
      {
        title: "Summer Sun Dress",
        price: "$180.00",
        rating: 4,
        img: "/img/showcase-img-5.jpg",
      },
      {
        title: "Urban Cargo Pants",
        price: "$210.00",
        rating: 5,
        img: "/img/showcase-img-6.jpg",
      },
    ],
  },
  {
    title: "Recently Added",
    items: [
      {
        title: "Leather Handbag",
        price: "$450.00",
        rating: 5,
        img: "/img/showcase-img-7.jpg",
      },
      {
        title: "Knitted Winter Cap",
        price: "$45.00",
        rating: 4,
        img: "/img/showcase-img-8.jpg",
      },
      {
        title: "Cozy Woolen Scarf",
        price: "$65.00",
        rating: 5,
        img: "/img/showcase-img-9.jpg",
      },
    ],
  },
  {
    title: "Top Rated",
    items: [
      {
        title: "Colorful Pattern Shirt",
        price: "$238.85",
        rating: 5,
        img: "/img/showcase-img-1.jpg",
      },
      {
        title: "Summer Sun Dress",
        price: "$180.00",
        rating: 5,
        img: "/img/showcase-img-5.jpg",
      },
      {
        title: "Leather Handbag",
        price: "$450.00",
        rating: 5,
        img: "/img/showcase-img-7.jpg",
      },
    ],
  },
];
